# Generated by Django 6.0.4 on 2026-08-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
