# Generated by Django 6.0.4 on 2026-08-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_video_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_2_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_3_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
