# Generated by Django 6.0.4 on 2026-08-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_project_image_2_paragraph_project_image_3_paragraph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='paragraph',
            field=models.TextField(blank=True),
        ),
    ]
