# Generated by Django 6.0.4 on 2026-08-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_project_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='paragraph',
        ),
    ]
