# Generated by Django 6.0.4 on 2026-08-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_project_paragraph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Project Image 1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Project Image 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_2_paragraph',
            field=models.TextField(blank=True, null=True, verbose_name='Image 2 Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Project Image 3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_3_paragraph',
            field=models.TextField(blank=True, null=True, verbose_name='Image 3 Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_paragraph',
            field=models.TextField(blank=True, null=True, verbose_name='Image 1 Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Project Active'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, null=True, verbose_name='Live Demo URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, help_text='Example: Python, Django, HTML, CSS, JavaScript, MySQL', max_length=500, verbose_name='Technologies Used'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/', verbose_name='Project Demo Video'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_paragraph',
            field=models.TextField(blank=True, null=True, verbose_name='Video Description'),
        ),
    ]
