# Generated by Django 6.0.4 on 2026-08-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_project_description_alter_project_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/covers/'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
