# Generated by Django 6.0.4 on 2026-08-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_project_cover_image_project_cover_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('django', 'Django'), ('Full Stack', 'Full Stack'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Web Application', 'Web Application'), ('Other', 'Other')], default='other', max_length=100),
        ),
    ]
