# Generated by Django 6.0.4 on 2026-08-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='recent',
            field=models.BooleanField(default=False, verbose_name='Recent Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('django', 'Django'), ('full stack', 'Full Stack'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('web application', 'Web Application'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Project Active'),
        ),
    ]
